# Generated by Django 2.2.4 on 2019-08-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(blank=True, default=18),
        ),
    ]
