# Generated by Django 2.2.4 on 2019-08-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBModule', '0002_auto_20190804_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='createTime',
        ),
    ]
